frase = str('Curso em Video Python')
print(f'A frase de teste será: {frase}')
print(f'A letra de posição 9 é: {frase[9]}')
print(f'A string entre a posição 9 e 13 é: {frase[9:13]}')
print(f'O comprimento da frase é: {len(frase)} caracteres')
print(f'Existem {frase.count('o')} letras "o" na frase')
print(f'Posição da palavra "android" na frase: {frase.find('android')}')
print(f'Posição da palavra "Python" na frase: {frase.find('Python')}')
print(f'Existe a palavra "Curso" na frase? {'Curso' in frase}')
print(f'Existe a palavra "android" na frase? {'android' in frase}')
print(frase.replace('Python','JavaScript'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
dividido = frase.split()
print(f'Lista com a minha frase dividida >> {dividido}')
print(f'Palavra de posição 2 na lista >> {dividido[2]}')
print(f'Caractere de posição 3 na palavra de posição 0 na minha lista >> {dividido[0] [3]}')
print(f'Juntando a minha frase dividida agora com um tracinho >> {'-'.join(dividido)}')